package com.anigame.ticket_services.domain.enums;

public enum PaymentStatusEnumEntity {
    PENDING,
    APPROVED,
    FAILED,
    CANCELED,
    REFUNDED,
    CONTESTED,
    CONFIRMED,//WAITING_FOR_BALANCE_CAPTURE, ESSE STATUS SIGNIFICA QUE O PEDIDO QUE ESTAVA COM STATUS APROVADO FOI TRATADO E OS TICKETS FORAM CRIADOS E AGORA SÓ FALTA CAPTURAR O DINHEIRO
    PAID
}
