server:
  port: 8080

spring:
  application:
    name: ticket-services
  datasource:
    #url:  jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false #Evita queries fora da transação.
  #  properties:
  #    hibernate:
  #      default_schema: authentication_services
  #      format_sql: true
  #  show-sql: true
  flyway:
    enabled: true
    schemas: ticket_services # O schema que esta aplicação irá gerenciar
    locations: classpath:db/migration/authentication_services # Diretório de scripts específico
    # flyway.table=flyway_schema_history_schema1 # Opcional: Para usar uma tabela de histórico única por schema
    table: flyway_schema_history_authentication_services
  cloud:
    openfeign:
      client:
        config:
          EventServicesClient:
            url: ${EVENT_SERVICES_URL}
          AuthenticationServicesClient:
            url: ${AUTHENTICATION_SERVICES_URL}

app:
  url: ${FRONTEND_URL}
  port: ${FRONTEND_PORT}
  verify-email-endpoint: ${FRONTEND_VERIFY_ENDPOINT}
  new-password-endpoint: ${FRONTEND_NEW_PASSWORD_ENDPOINT}

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600           # 1 hour
  refresh-token: 28800         # 8 hours
  auth-validation-token: 900   # 15 minutes
  new-password-token: 300      # 5 minutes

topics:
  register-user: "register-user.topic.v1"
  send-email: "send-email.topic.v1"

efi:
  pix-base-url: https://pix.api.efipay.com.br
  credit-card-base-url: https://cobrancas.api.efipay.com.br
  client-id: Client_Id_52f4c6f77449efd1bde73fa35d8b660a2c426df9
  client-secret: Client_Secret_89de70b0bc913ff23d72e01dd25168467ebaa8cb
  certificate-path: certs/producao-686823-ani-teste-cert.p12
  certificate-password:
  sandbox: false
  original-ticket-price: 3000
  pix-key: 6ed3f4f0-e132-4e36-8593-da28c736be9a
  qr-code-expiration-time: 3600
  charge-notification-url: https://www.anigame.com.br/v1/webhook/charges

  credit-card-fee-type: PERCENTAGE #FIXED/PERCENTAGE
  credit-card-fee-value: 3.49
  pix-fee-type: PERCENTAGE #FIXED/PERCENTAGE
  pix-fee-value: 1.19


event:
  ticket-limit-per-user: 3

#logging: #essa configuração de log serve pra mostrar os logs de debug do feignclient no console
#  level:
#    feign: DEBUG
