server:
  port: 8080

spring:
  application:
    name: ticket-services
  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

    jpa:
      open-in-view: false #Evita queries fora da transação.
    #hibernate:
    #  ddl-auto: create-drop
    #  ddl-auto: update
    #show-sql: true
    #defer-datasource-initialization: true
    #properties:
    #  hibernate:
    #    format_sql: true
  cloud:
    openfeign:
      client:
        config:
          EventServicesClient:
            url: http://event-services:8080
          AuthenticationServicesClient:
            url: http://authentication-services:8080

app:
  url: http://localhost
  port: 8085
  verify-email-endpoint: /auth/verify-user-account
  new-password-endpoint: /auth/new-password

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600           # 1 hour
  refresh-token: 28800         # 8 hours
  auth-validation-token: 900   # 15 minutes
  new-password-token: 300      # 5 minutes

topics:
  register-user: "register-user.topic.v1"
  send-email: "send-email.topic.v1"

efi:
  client-id: Client_Id_4d5a212bae6ba3534c9c60fc1004233494d343d6
  client-secret: Client_Secret_578f36b9cee8b6c8aaade1789449349b1c1bda12
  certificate-path: certs/homologacao-686823-ani-teste-cert-hom.p12
  sandbox: true
  original-ticket-price: 3000 #valor em centavos OBS-IMPORTANTE: esse valor deve ser SEMPRE PAR pois se for impar o valor da meia entrada não será inteiro e dará problema de arredondamento !!!
  pix-key: 71cdf9ba-c695-4e3c-b010-abb521a3f1be
  qr-code-expiration-time: 3600



