server:
  port: 8080

spring:
  application:
    name: ticket-services
  datasource:
    #url:  jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false #Evita queries fora da transação.
  #  properties:
  #    hibernate:
  #      default_schema: authentication_services
  #      format_sql: true
    show-sql: true
  flyway:
    enabled: true
    schemas: ticket_services # O schema que esta aplicação irá gerenciar
    locations: classpath:db/migration/authentication_services # Diretório de scripts específico
    # flyway.table=flyway_schema_history_schema1 # Opcional: Para usar uma tabela de histórico única por schema
    table: flyway_schema_history_authentication_services
  cloud:
    openfeign:
      client:
        config:
          EventServicesClient:
            url: ${EVENT_SERVICES_URL}
          AuthenticationServicesClient:
            url: ${AUTHENTICATION_SERVICES_URL}

app:
  url: ${FRONTEND_URL}
  port: ${FRONTEND_PORT}
  verify-email-endpoint: ${FRONTEND_VERIFY_ENDPOINT}
  new-password-endpoint: ${FRONTEND_NEW_PASSWORD_ENDPOINT}

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600           # 1 hour
  refresh-token: 28800         # 8 hours
  auth-validation-token: 900   # 15 minutes
  new-password-token: 300      # 5 minutes

topics:
  register-user: "register-user.topic.v1"
  send-email: "send-email.topic.v1"

efi:
  client-id: Client_Id_4d5a212bae6ba3534c9c60fc1004233494d343d6
  client-secret: Client_Secret_578f36b9cee8b6c8aaade1789449349b1c1bda12
  certificate-path: certs/homologacao-686823-ani-teste-cert-hom.p12
  sandbox: true
  original-ticket-price: 3000 #valor em centavos OBS-IMPORTANTE: esse valor deve ser SEMPRE PAR pois se for impar o valor da meia entrada não será inteiro e dará problema de arredondamento !!!
  pix-key: 71cdf9ba-c695-4e3c-b010-abb521a3f1be
  qr-code-expiration-time: 3600
