server:
  port: 8080

spring:
  application:
    name: ticket-services
  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

    #jpa:
    #hibernate:
    #  ddl-auto: create-drop
    #  ddl-auto: update
    #show-sql: true
    #defer-datasource-initialization: true
    #properties:
    #  hibernate:
    #    format_sql: true
app:
  url: http://localhost
  port: 8085
  verify-email-endpoint: /auth/verify-user-account
  new-password-endpoint: /auth/new-password

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
expire-times:
  access-token: 3600           # 1 hour
  refresh-token: 28800         # 8 hours
  auth-validation-token: 900   # 15 minutes
  new-password-token: 300      # 5 minutes

topics:
  register-user: "register-user.topic.v1"
  send-email: "send-email.topic.v1"


